services:
  pyaravis_build:
    build: .
    container_name: pyaravis_build
    tty: true
    stdin_open: true
    volumes:
      - ./src:/src
      - ./pyaravis:/pyaravis
    command: ["/src/run.sh"]
