services:
  pyaravis_build:
    build: .
    container_name: pyaravis_build
    tty: true
    stdin_open: true
    volumes:
      - ./run.sh:/run.sh
      - ./pyaravis:/pyaravis
      - ./tools:/tools
      - ./template:/template
    command: ["/run.sh"]
